import Link from 'next/link';
import Image from 'next/image';
import './global.css';
import { auth } from '../lucia';
import { cookies } from 'next/headers';
import { Logout } from '../components/logout';

export const metadata = {
  title: 'KAPPA',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authRequest = auth.handleRequest({
    request: null,
    cookies,
  });
  const session = await authRequest.validate();
  const user = session?.user;
  return (
    <html lang="en">
      <body>
        <nav className="h-32 p-8 flex justify-between items-center bg-cover bg-[url('https://images.unsplash.com/photo-1691683018612-10abe7863978')]">
          <div className="font-mono text-3xl">
            <span className="bg-white/50 text-black px-4">KAPPA</span>
          </div>
          <div>
            {!user && <Link href="/login">Sign in</Link>}
            {user && (
              <div className="flex flex-row gap-4">
                <div className="flex flex-col gap-2 items-center text-black">
                  {user.avatarUrl && (
                    <Image
                      className="rounded-xl border-white border-2"
                      src={user.avatarUrl}
                      alt="avatar"
                      width={50}
                      height={50}
                    />
                  )}
                  <span className="bg-white/50 px-4">{user.username}</span>
                </div>
                <Logout>🔋</Logout>
              </div>
            )}
          </div>
        </nav>
        <main className="flex flex-col gap-8 pt-8 container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
